<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?php echo _('Páginas'); ?></h1>
        <div class="w-xxxx-12 cont_header_panel" style="">
            <div class="_wrapp_form_serch">
                <form name="buscarGrid" action="" method="get" id="paginar">                
                    <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                </form>
                  <a href="<?php echo $MyRequest->url(FRM_PAGINAS); ?>" class="_btn_new">Nuevo</a>
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin ">
        <table id="jqGrid"></table>
        <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);


    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'blog',
        redirectOnSelectRow:true,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '<?=$MyRequest->link(FRM_PAGINAS)?>',
        pathData : '<?=$MyRequest->url(LISTA_PAGINAS)?>',
        error : "<?=_('No hay registros')?>",
        deleteFunction : "EliminarPagina",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Callback')?>', name: 'callback',  hidden:true, width: 50 },
            { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
            { label: '<?=_('Nombre')?>', name: 'nombre', width: 250 },
            { label: '<?=_('Url')?>', name: 'url', width: 250 },
            { label: '<?=_('Constante')?>', name: 'constante', hidden:isGridMobile, width: 250 },
            { label: '<?=_('ACL')?>', name: 'resource', hidden:isGridMobile, width: 200 },
            { label: '<?=_('Modulo')?>', name: 'modulo', hidden:isGridMobile, width: 200 },
            { label: '<?=_('PHP')?>', name: 'php', hidden:isGridMobile, width: 250 },
         
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
            }
        ],
        subGrid: isGridMobile,
        subGridRowExpanded: showChildGrid,
        width:1420
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a href="<?=$MyRequest->link(FRM_PAGINAS)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar"><span class="icon icon-editar"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton1 + boton2;
}

function showChildGrid(parentRowID, parentRowKey) {
    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";
    
    if($(window).width() <= 767) {
      
        var php  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_php"]').text();
        var constante  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_constante"]').text();
        var resource  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_resource"]').text();
        var modulo  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_modulo"]').text();
     
        $('#' + parentRowID).append('<p>URL: '+php+'</p>');
        $('#' + parentRowID).append('<p>Idioma: '+constante+'</p>');
        $('#' + parentRowID).append('<p>ACL: '+resource+'</p>');
        $('#' + parentRowID).append('<p>Modulo: '+modulo+'</p>');
       
    }
}

</script>
